version: "3.3"
services:
  layout-constructor-ui-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8181:80
    volumes:
      - .:/code
      - /code/node_modules
    networks:
      - layout_constructor_ui

networks:
  layout_constructor_ui: